image: node:8.11.2

pages:
  script:
    - mkdir .public
    - cp -r docs/. .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - tz-chart
